canada-ca/Open_First_Whitepaper

3_Open_Source_Software.md
I do think the Free Beer catches peoples attention. This probably should have been two issues so that they could have been discussed separately.
=> Suggestions to History & Free Beer?

7_Next_Steps.md
Added bullet-points for communications & a heading for procurement. Government needs to have a clear policy for buying open source software and I've suggested some options to look at.
=> Adding steps for communications & procurement

7_Next_Steps.md
Adding a few ways to government can contribute back to the open source community.
=> core infrastructure initiative & conferences

8_Definitions.md
https://en.wikipedia.org/wiki/Open_standard#Joint_IEEE.2C_ISOC.2C_W3C.2C_IETF_and_IAB_Definition
=> Basically the W3C's summary of a open standard

8_Definitions.md
Basically from https://en.wikipedia.org/wiki/Open-source_software
=> Definition of open source

8_Definitions.md
There should be some comparison with OSS.
=> Expanding a bit on Free Software

3_Open_Source_Software.md
taken from 18F https://github.com/18F/open-source-policy/blob/master/policy.md
=> Benefits of OSS

4_Open_Source_Code.md
great wording here should be re-used in the GC policy https://github.com/18F/open-source-policy/blob/master/policy.md
=> Pulling from 18F

8_Definitions.md
definition from https://www.oshwa.org/definition/
=> Open source hardware

2_Open_Standards.md
These two sentences have been taken from the Ontario government's document:
https://www.ontario.ca/page/open-default-new-way-forward-ontario
=> Adding the committment to action

5_Open_Markets.md
This was a regular point within the FWD50 discussions.  I'd like to see more focus on building a vibrant ecosystem of collaborators than I am interested in the focus on the competitions.  Sure, competition can be useful, but investment in open communities from government is still very new in Canada.
=> Open source ecosystems

4_Open_Source_Code.md
see https://github.com/18F/open-source-policy/blob/master/policy.md
=> we need to set a default position

9_Open Platforms
Proposing first iteration of the Open Platform Section based on the approved development stack @Public Service Commission.
=> Update 9_Open Platforms

8_Definitions.md
definition from https://github.com/DISIC/foss-contrib-policy-template/blob/master/FOSSPolicyTemplate.md
=> Chainging order and adding version control definition

2_Open_Standards.md, 3_Open_Source_Software.md, 7_Next_Steps.md
Modifying some phrasing and adding a proposal for the creation of a process to ensure documents/writings produced by the government of Canada meet bilingual standards by the time they hit the master branch.
=> Adding next step/Adjusting phrasing 

4_Open_Source_Code.md, 5_Open_Markets.md
Adding sources to reinforce some points that were made. 
Added a section in open markets to address points from a recent and relevant article released by CBC (http://www.cbc.ca/news/politics/information-technology-alex-benay-balsillie-procurement-open-government-us-firms-phoenix-1.4414786).
=> Qualifying existing - Adding Open Market Aim

4_Open_Source_Code.md, 5_Open_Markets.md
It was requested that I put inline links rather than citations/sources at the bottom of the page.
=> Removing Sources - Adding inline links

2_Open_Standards.md
Hello from the Open Standards team in GOVUK :-)
Spotted a some typos in this excellent document.
=> Fix a few typos

9_Preferred_Open_Platforms.md
Rephrasing some parts, improving formatting, and fixing typos.
=> Formatting / Typos

9_Preferred_Open_Platforms.md
Resolves "9_Preferred_Open_Platforms.md:51: MD009 Trailing spaces"
=> Removed trailing whitespace that is breaking the build

8_Definitions.md
=> Updates to Definitions page

8_Definitions.md
=> chore: fix list spacing issue in Definitions

3_Open_Source_Software.md
Note that the noun is spelled "license" in the US, but "licence" in the UK and Canada.  The verb is spelled "license" everywhere.
=> Proofreading

en/2_Open_Standards.md, en/3_Open_Source_Software_Use.md, en/4_Open_Source_Software_Contribution.md, en/5_Open_Markets.md, fr/2_Normes_ouvertes.md, fr/3_Logiciel_libre_Utilisation.md, fr/4_Logiciel_libre_Contribution.md, fr/5_Marchés_ouverts.md, package-lock.json
Modified sections related to Open Source Software to reprensent two
dimensions: Use and Contributions. Also modified headers.
=> Modify sections

.markdown-link-check.json
Server takes awhile to load for me and still is failing with the 30 second timeout
=> chore: Ignore http://www.austlii.edu.au/

en/1_Introduction.md, en/2_Open_Standards.md, en/3_Open_Source_Software_Use.md, en/4_Open_Source_Software_Contribution.md, en/5_Open_Markets.md, en/6_Open_Culture.md, fr/1_Introduction.md, fr/2_Normes_ouvertes.md, fr/3_Logiciel_libre_Utilisation.md, fr/4_Logiciel_libre_Contribution.md, fr/5_Marchés_ouverts.md, fr/6_Culture_ouverte.md
Updated all sections with new content:
- Fix typos and syntax in all documents
- OSS Use: 
- Move Copyright to OSS Contribution/Intellectual Property
- OSS Contribution: 
- Define Contribution
- Add Intellectual Property section with Copyright section from OSS Use
- Open Culture:
- Add "Entrenched Behavior and Fear of the Unknown" section
=> Update sections 1-6

en/3_Open_Source_Software_Use.md
Just send to the front page instead
=> Fix broken link

fr/3_Logiciel_libre_Utilisation.md
Envoyer à la page d'entrée qui sera toujours valide.
Send to front page, which will always be valid.
=> Correction du lien / fix URL

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE/general.md, .github/dependabot.yml, .github/workflows/cspell.yml, .github/workflows/link-check.yml, .github/workflows/markdownlint.yml, .travis.yml, README.md
---
name: General
about: This a gerneral pull request template to be used for any reason
title: ''
labels: ''
assignees: ''
---
=> chore: Add CI setup from template repo

.github/workflows/link-check.yml, .github/workflows/markdownlint.yml
---
name: General
about: This a gerneral pull request template to be used for any reason
title: ''
labels: ''
assignees: ''
---
=> chore: Ignore Dependabot branch pushes

.github/workflows/markdownlint-problem-matcher.json, .github/workflows/markdownlint.yml
---
name: General
about: This a gerneral pull request template to be used for any reason
title: ''
labels: ''
assignees: ''
---
=> chore: Add Markdownlint problem matcher

.github/workflows/cspell-problem-matcher.json, .github/workflows/cspell.yml
---
name: General
about: This a gerneral pull request template to be used for any reason
title: ''
labels: ''
assignees: ''
---
=> chore: Add cSpell problem matcher for CI
